sudo: required
services:
  - docker

before_install:
  - docker build -t ujjwalbarapatre101989/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ujjwalbarapatre101989/docker-react npm run test